### ISSUE TITLE
Sensors in HA stopped updating - errors in SDR to Home Assistant add-on log

### ISSUE THREAD

**Issue by nero0954** [thejeffreystone/hassio_addons#21]
Currently running HA OS core-2021.11.4.

MQTT output from SDR to Home Assistant add-on was working fine after update to HA OS core-2021.11.4.

Noticed that all my weather station sensors stopped updating around midday today and noted errors in the add-on log

I've tried re-starting the add-on, re-building the add-on and uninstalling and reinstalling the add-on , but no difference

Add-on log as below - any help with the error appreciated

Starting RTL_433 with parameters:
MQTT Host = 192.168.0.xxx
MQTT port = 1883
MQTT User = user
MQTT Password = password
MQTT Topic = rtl_weather
MQTT Retain = true
FREQUENCY = -f 868.3M
PROTOCOL = -R 32
UNITS = si
DISCOVERY_PREFIX = homeassistant
DISCOVERY_INTERVAL = 600
DEBUG = false
rtl_433 version 21.05-143-g4ca3cb0d branch master at 202111171123 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/root/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
New defaults active, use "-Y classic -s 250k" for the old defaults!
Publishing MQTT data to 192.168.0.xxx port 1883
Publishing device info to MQTT topic "rtl_weather[/model][/id][/channel:0]".
Publishing events info to MQTT topic "rtl_weather/events".
Publishing states info to MQTT topic "rtl_weather/states".
Registered 1 out of 200 device decoding protocols [ 32 ]
Found Rafael Micro R820T tuner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exact sample rate is: 1000000.026491 Hz
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/scripts/rtl_433_mqtt_hass.py", line 434, in mqtt_message
    bridge_event_to_hass(client, msg.topic, data)
  File "/scripts/rtl_433_mqtt_hass.py", line 500, in bridge_event_to_hass
    if not instance:
UnboundLocalError: local variable 'instance' referenced before assignment
[R82XX] PLL not locked!
Sample rate set to 1000000 S/s.
Tuner gain set to Auto.
Tuned to 868.300MHz.
MQTT Connected...
MQTT Connection established.

**Comment by thejeffreystone** [comment]
Upgrading my instances to 2021.11.4 to see if I can track this down. That looks as if a device didn't have a unique identifier
