### ISSUE TITLE
Random outages, appears to not communicat with radio.

### ISSUE THREAD

**Issue by mattlward** [thejeffreystone/hassio_addons#24]
Both of my sensors go dead and I have the following in my logs until I restart the add-on.
`
MQTT Connection failed...
MQTT Connected...
MQTT Connection established.
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
cb transfer status: 5, canceling...
LIBUSB_ERROR_NOT_FOUND: Entity not found!
Check your RTL-SDR dongle, USB cables, and power supply.
WARNING: async read failed (-5).
Library error -5, exiting...
`

I am running the latest version of the add-on in HA version as follows:
`
## System Health

version | core-2022.2.6
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.0-9-amd64
arch | x86_64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4913
Installed Version | 1.22.0
Stage | running
Available Repositories | 978
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.11
disk_total | 218.1 GB
disk_used | 29.6 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Backup Hassio to Google Drive (1.7.2), Dropbox Sync (1.3.0), Duck DNS (1.14.0), File editor (5.3.3), Log Viewer (0.12.2), RPC Shutdown (2.2), WireGuard (0.6.0), Mosquitto broker (6.0.1), SSH & Web Terminal (10.0.2), Samba share (9.5.1), TasmoAdmin (0.16.0), Glances (0.14.2), Check Home Assistant configuration (3.9.0), DHCP server (1.2), Network UPS Tools (0.9.1), Samba Backup (5.0.0), Node-RED (10.4.0), Portainer (2.0.0), SDR to Home Assistant (0.1.6b), Home Assistant Google Drive Backup (0.105.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 6
views | 15
mode | storage

</details>
`

**Comment by thejeffreystone** [comment]
hmm. Let me upgrade mine and see if I get the same.

**Comment by mattlward** [comment]
I have had it happen in the current major and the last major as well.

**Comment by mattlward** [comment]
Btw, do you know of a known working doorbell button?

**Comment by mattlward** [comment]
I'm looking for a way to create an automation that looks for a bad log entry a would restart the addon.  Could that function be added to the watchdog in the addon?

**Comment by thejeffreystone** [comment]
That might help. If you turn debug on in the add-on, it will log the messages it is getting. I notice mine doesn't update for long periods, but it appears those are periods in which the sensor value didn't change. I mean I have an acurite sensor outside that sends both humidity and temp. They come in the same message to mqtt. And right now the Temp sensor updated 5 mins ago, and the humidity 1 minute ago. So unless the value changes Home Assistant is not marking it updated. I wonder if that is causing some of the issue.

**Comment by mattlward** [comment]
Mine update very often.  Is there a way to dump the log in an auto?
Restarting the addon clears the log.  Also without debug my log is normally
empty.

**Comment by thejeffreystone** [comment]
Yeah, since that thing is constantly reading the SDR I figured it could get nuts log wise, so I keep the messages suppressed. The only way I know of access the log is via docker. I tend to just use the log on the add-one and copy out what I need. 

I been playing with updates tonight on my beta box, but didn't get anywhere other than I might have some more properties I can add. I know that some of the devices have a USB issue so I have always used a hub between the SDR and my device. Not sure if that is why I dont see an issue.

**Comment by mattlward** [comment]
Update 1.9b just appeared and now installed.

**Comment by mattlward** [comment]
Reverting to previous version.  The following error now happens and nothing reads:
`
Traceback (most recent call last):
  File "/scripts/rtl_433_mqtt_hass.py", line 28, in <module>
    WHITELIST_ENABLE = os.environ['WHITELIST_ENABLE']
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'WHITELIST_ENABLE'
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sample rate set to 250000 S/s.
Tuner gain set to Auto.
Tuned to 433.920MHz.
MQTT Connected...
MQTT Connection established.
`

**Comment by mattlward** [comment]
And upon restore of old version the addon will not start:
```
No supported devices found.
Traceback (most recent call last):
  File "/scripts/rtl_433_mqtt_hass.py", line 28, in <module>
    WHITELIST_ENABLE = os.environ['WHITELIST_ENABLE']
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'WHITELIST_ENABLE'
```

**Comment by thejeffreystone** [comment]
0.1.11b should be working for SDR2MQTT and 0,3,12b should be for Acurite2MQTT

**Comment by mattlward** [comment]
Got it and yes it did fix the issue.

Thanks!
