### ISSUE TITLE
All sensors "unavailable" after fiew minutes

### ISSUE THREAD

**Issue by Giannuz** [thejeffreystone/hassio_addons#26]
I installed this addon yesterday and everything worked perfectly with my oregon sensors, this morning I updated to the latest version and the sensors seem to disappear after a couple of minutes after restarting the addon. sorry if this is a stupid question but as I said I have little experience with acurite2mqtt

**Comment by thejeffreystone** [comment]
That's not a stupid question. 

It seems to be a common issue, although I haven't been able to figure out why some people are getting that. 

I would turn on debug mode by clicking that debug option in the configuration and restart the add-on. Let me know if you see any errors.

**Comment by thejeffreystone** [comment]
I see some people reporting losing sensors / unavailable sensors on the rtl_433 project and the theory is its a range issue. The SDR is losing signal from the devices either to interference or something else. I think the SDR dongle doesn't have enough power. How far are the sensors from the antenna? Could it be a range issue?

**Comment by Giannuz** [comment]
I don't think it's a range issue because one of the sensors is like 1-2m away from the antenna and they were all working fine last night, I tried looking at the logs of the addon and here's what I found:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/scripts/rtl_433_mqtt_hass.py", line 443, in mqtt_message
    bridge_event_to_hass(client, msg.topic, data)
  File "/scripts/rtl_433_mqtt_hass.py", line 521, in bridge_event_to_hass
    publish_config(mqttc, key, model, instance, channel, mappings[key])
  File "/scripts/rtl_433_mqtt_hass.py", line 485, in publish_config
    manufacturer, model = model.split("-", 1)
ValueError: not enough values to unpack (expected 2, got 1)`

I get this after the normal "lines" with "MQTT Connection established" at the end, it appear after a few seconds and then all the sensors get lost.

The weirdest thing is that shortly after the restart all the sensor are available in home assistant and they seems to work fine but after a few seconds they are gone

**Comment by thejeffreystone** [comment]
ok, cool. Let me see if I can figure something out with that. 

I also just added a last_seen entity that is the timestamp the rtl_433 script last saw the device. Hoping that helps identify if there is something going on with that script.

**Comment by thejeffreystone** [comment]
Ok, when you get a chance update and lets see if I fixed that error. 

Looked like it was crashing because the device didn't have a manufacturer in the model value. We will see. Fingers crossed.

**Comment by thejeffreystone** [comment]
ok. Fixed that one.. I hope.,

**Comment by thejeffreystone** [comment]
0.1.11b should be working for SDR2MQTT and 0,3,12b should be for Acurite2MQTT

**Comment by Giannuz** [comment]
I updated and now everything works again! ty so much!
