### ISSUE TITLE
sdr2mqtt stops reporting due to error

### ISSUE THREAD

**Issue by FinestDice17** [thejeffreystone/hassio_addons#58]
Out of the blue this error starting occuring and ive only realized it due to uptime kuma that ive setup letting me know. This is a screen shot of whats happening in the logs. 
<img width="1258" alt="Screenshot 2023-10-24 at 1 56 27 PM" src="https://github.com/thejeffreystone/hassio_addons/assets/68380500/41f0df96-789b-4e65-afef-84bc98515cca">

**Comment by dilpish** [comment]
same problem
`DEBUG:Received Device Data from SDR and sent to MQTT: rtl_433/events : {"time": "2024-09-30 21:30:53+0300", "protocol": 17, "model": "Cardin-S466", "dipswitch": "---+-oo+-", "rbutton": "00L?", "mod": "ASK", "freq": 433.97059, "rssi": -5.21573, "snr": 12.84607, "noise": -18.0618}
Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/scripts/rtl_433_mqtt_hass.py", line 593, in mqtt_message
    bridge_event_to_hass(client, msg.topic, data)
  File "/scripts/rtl_433_mqtt_hass.py", line 667, in bridge_event_to_hass
    logging.warning("Device Id:{} doesn't appear to be a actual device. Skipping..".format(data['id']))
                                                                                           ~~~~^^^^^^
KeyError: 'id'`

**Comment by mrosandich** [comment]
I get the same error. Should be an easy fix:
 Remove the .format(data['id']))  since data['id'] doesn't exsist and noted by the  if "id" in data: logic.

 if "id" in data:
        instance = str(data["id"])
    else:
        instance = 0
        
    if instance == 0:
        logging.warning("Device Id:{} doesn't appear to be a actual device. Skipping..".format(data['id']))
        return
